services:
  rabbit-mq:
    image: rabbitmq
    ports:
      - 5672:5672


  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    ports:
      - 9200:9200 
    environment:
      - xpack.security.enabled=false
      - node.name=es01
      - cluster.name=rabbit_cluster
      - cluster.initial_master_nodes=es01

    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana: 
    image: docker.elastic.co/kibana/kibana:8.4.1
    depends_on:
      - es01
    
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - SERVERNAME=kibana
    
    ports:
      - 5601:5601
